dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: username
      password: password
      port: 5432
      dbname: yourdatabase
      schema: public
      threads: 4